---
- name:  Create and mount ceph volumes with loadgens
  hosts: director
  become: yes
  vars:                                          #number of vms can increased by addming more vms names, and floating ips respectively
    number_of_vms: 9
    vm: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
    volume_size: 200
    numebr_of_ceph_volumes_perloadgen: 2
    volume_name: [vdb]

  tasks:
   - name: Create volume
     shell: |
            source /home/osp_admin/r62rc
            openstack volume create  --size {{item[0]}} {{item[2]}}.{{item[1]}}
     with_nested:
       - '{{volume_size}}'
       - '{{volume_name}}'
       - '{{vm}}'
     when: item[2] < number_of_vms

   - name: Mount volumes with loadgens
     shell: |
            source /home/osp_admin/r62rc
            openstack server add volume  vm{{item[1]}} {{item[1]}}.{{item[0]}}
     with_nested:
       - '{{volume_name}}'
       - '{{vm}}'
     when: item[1] < number_of_vms
